# Generated by Django 2.0.2 on 2018-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.FileField(upload_to='profilepics/%Y/%m/%d/%H/%M/%S//'),
        ),
    ]
