# Generated by Django 2.0.2 on 2018-03-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_doctor_patient_slot_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Time', models.TimeField()),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='Doctor_id',
        ),
        migrations.RemoveField(
            model_name='timings',
            name='contact_time',
        ),
        migrations.AddField(
            model_name='timings',
            name='Contact_Time',
            field=models.TimeField(default='12:30'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
