# Generated by Django 2.0.2 on 2018-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='Slot_Time',
            field=models.CharField(max_length=15),
        ),
    ]
